### ISSUE TITLE
Copy logic regarding warning to stale issue checker

### ISSUE THREAD

**Issue by astrofrog** [OpenAstronomy/baldrick#68]
The stale issue checker will currently close an issue even if there has not already been a warning. We should use the same logic as for the stale PR checker to check when the warning was posted, if any.

**Comment by bsipocz** [comment]
and is that an issue? presumably the was a comment left when the `close?` label was added.

**Comment by astrofrog** [comment]
@bsipocz - sorry I mean the comment from the bot - basically the bot needs to put a warning that the issue will be closed in X time, and then only close it if it's actually warned people it would do so.

**Comment by bsipocz** [comment]
sure, but I still think it not fully necessary if we assume that the label was added with some comment (and we have the common understanding that if nothing happens for a `close?` issue for a month, well, then it gets closed).

**Comment by astrofrog** [comment]
I agree - but it's an easy fix, I'll do it shortly.
