### ISSUE TITLE
Reuse Cpython bots

### ISSUE THREAD

**Issue by bsipocz** [OpenAstronomy/baldrick#79]
I'm not sure it's practical, but CPython has tons of bots to do various tasks.

E.g. https://github.com/python/bedevere/ labels PRs etc, we might want to reuse them, or at least some of the logic they have?

(The other two bots are less relevant, one checks whether the CLI is signed by the contributor, and the other is for backports)

**Comment by pllim** [comment]
At a glance, it does not seem as easily customizable as `baldrick` here, but worth exploring if we happen to encounter CPython devs in one of the conferences and they are willing to provide consultation.

**Comment by bsipocz** [comment]
Well, the appropriately cunning plan could be to get them use and contribute baldrick :)
