### ISSUE TITLE
Checks can be re-run

### ISSUE THREAD

**Issue by Cadair** [OpenAstronomy/baldrick#86]
Now that #73 is in, it appears there is a "re-run" button on the checks page which triggers a POST to the bot. We should look into rerunning the check if this is clicked.

**Comment by pllim** [comment]
What button? I don't see any buttons.

**Comment by Cadair** [comment]
![image](https://user-images.githubusercontent.com/1391051/64271880-12acaa00-cf36-11e9-94a8-f9232dc34eb0.png)

On the checks tab.

Also see this section of the docs: https://developer.github.com/v3/activity/events/types/#checkrunevent

**Comment by pllim** [comment]
Oh, I can't see it. Maybe only author or maintainer sees it.

**Comment by Cadair** [comment]
Oh yeah probably need commit rights.
