### ISSUE TITLE
Disable merge button for certain labels

### ISSUE THREAD

**Issue by bsipocz** [OpenAstronomy/baldrick#90]
What a cunning plan!

It would be nice to be able to disable the merge button while a PR has a certain label set.

E.g. https://github.com/astropy/astropy/pull/9282 needs to be tested in a downstream package, so ideally it should not be merged until the `needs-downstream-testing` label is present. I suspect this logic could be used for other labels, too.

**Comment by Cadair** [comment]
by "disable merge button" I assume you mean set a failing check?

**Comment by bsipocz** [comment]
something stronger, to have the greyed out merge button, similarly when no one yet approved it.

**Comment by Cadair** [comment]
Is that something you can do via the github API?

**Comment by bsipocz** [comment]
I'm not sure. Did I mention it was cunning plan? 😏

**Comment by Cadair** [comment]
The way I *know* will work is that you setup a specific check for the label check, and then make it a required check using protected branches. I can't see anything in the API about blocking merge.

**Comment by bsipocz** [comment]
Oh, that would work quite nicely I suppose.

**Comment by stefanv** [comment]
It would be neat to have this. Just landed here after skimage wanted the same, but I believe it would have to be implemented on a GH level.

**Comment by bsipocz** [comment]
I don't think we can grey out the merge button, but there could be a required workflow that fails when the label is present.  

I think people with just write level permissions would not be able to override such a branch protection.

**Comment by stefanv** [comment]
This is what we have on scikit-image, but it's not great when newcomers get a red cross on their PR, without the ability to turn it green themselves :/  [In our case, the requirement is to have a `type: ...` label, for changelog purposes.]

**Comment by bsipocz** [comment]
Ah, the circle closes, I believe I was complaining about that failing labelling job myself 😂

**Comment by pllim** [comment]
FWIW I think this can be accomplished in Actions now, without `baldrick`. For example: https://www.neilmacy.co.uk/blog/github-action-to-block-merging + branch protection rules.

**Comment by bsipocz** [comment]
Yes, this is what we chatted about above that we can currently have a failing required workflow/job controlled by a label, but that red cross could be annoying and or confusing to contributors (and also reviewers, I certainly could get less attention from maintainers' on some of my PRs when there were CI failures, even if they were clearly unrelated)

**Comment by pllim** [comment]
If the red cross only shows up when a maintainer chooses to apply a label, then it would be green most of the time. Personally I will be okay with that.

There is also a totally unrelated request for GitHub to just make all PRs draft by default (merge button is automatically disabled) but after so many years, that request is still open.

**Comment by bsipocz** [comment]
Yeap, original use case for this issues, the downstream testing label, would indeed be rare, but skiimage's case is the opposite, it would not allow merging before adding certain labels.

**Comment by pllim** [comment]
Hmm... You could also require N number of approvals before merge. I think that disables the merge button until approvals given without any red X ?

**Comment by pllim** [comment]
Regardless, I feel like this has nothing to do with baldrick anymore. Is there an issue over at ~sklearn~ scikit-image we can continue on?

**Comment by bsipocz** [comment]
Yes, agreed on closing this for baldrick. It was a cunning plan that didn't work out 🤣
